# Generated by Django 4.0.5 on 2022-06-14 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_provincias_perfiles_direccion_ciudades_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiles',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='perfiles',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='perfiles',
            name='telefono',
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preguntar_por', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=120)),
                ('referencias', models.TextField()),
                ('telefono', models.CharField(max_length=13)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.ciudades')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.perfiles')),
            ],
        ),
    ]
