# Generated by Django 4.0.5 on 2022-06-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0003_productos_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
