# Generated by Django 4.0.5 on 2022-06-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0004_productos_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
