# Generated by Django 4.0.5 on 2022-06-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0006_productos_en_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiendas',
            name='logo',
            field=models.ImageField(default='/static/img/tienda_mia.png', upload_to='logos'),
        ),
    ]
