# Generated by Django 4.0.5 on 2022-06-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0008_alter_tiendas_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='retiro_en',
            field=models.CharField(default='Domicilio', max_length=30),
        ),
    ]
